# Generated by Django 6.0.6 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Satyamoorthy BCA', max_length=100)),
                ('phone_number', models.CharField(default='+919043198508', max_length=15)),
                ('section', models.CharField(default='III BCA - D Section', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailycode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='attendance',
            name='distance_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
